# permissions for end users to view demohollicubes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demohollicube-viewer-role
rules:
- apiGroups:
  - gpaas.hollicube.io
  resources:
  - demohollicubes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gpaas.hollicube.io
  resources:
  - demohollicubes/status
  verbs:
  - get
